# 服务配置:https://goframe.org/pages/viewpage.action?pageId=44449486
server:
  # 基本配置
  address: ":10001"                      # 本地监听地址
  serverAgent: "Hamster_Chat"             # 服务端Agent信息。默认为"GoFrame HTTP Server"
  nameToUriType: 1                      # 服务名称转换为URI的类型，1表示驼峰

  # 接口文档
  openapiPath: "/api.json" # OpenAPI接口文档地址
  swaggerPath: "/swagger"  # 内置SwaggerUI展示地址

  # 服务日志配置（访问日志，错误日志）
  logPath: "./logs/server_log"          # 日志文件目录
  logStdout: true                       # 日志输出到终端
  accessLogEnabled: true                # 是否记录访问日志
  accessLogPattern: "access.{Ymd}.log"  # 访问日志文件
  errorStack: false                     # 是否记录错误堆栈信息
  errorLogEnabled: true                 # 是否记录错误日志
  errorLogPattern: "error.{Ymd}.log"    # 错误日志文件

# 日志配置:https://goframe.org/pages/viewpage.action?pageId=1114388
logger:
  level: "all"            # 日志级别
  stdout: false           # 是否输出到终端
  path: "./logs"          # 日志输出目录
  file: "log-{Y-m-d}.log" # 输出日志命名格式。

# 数据库ORM配置:https://goframe.org/pages/viewpage.action?pageId=1114245
database:
  logger:
    level: "all"            # 日志级别
    stdout: false           # 是否输出到终端
    path: "./logs/db"       # 日志输出目录
    file: "db-{Y-m-d}.log"  # 输出日志命名格式。
  default:
    link: "mysql:chat_im:WwZSxS4dkaFSCsZ3@tcp(120.24.211.49:3306)/chat_im" # 数据库链接
    timezone: "Asia/Shanghai" # 时区
    debug: false              # 是否开启调试模式


