
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:chat_im:WwZSxS4dkaFSCsZ3@tcp(120.24.211.49:3306)/chat_im" # 数据库链接
        jsonCase: Snake # 蛇型json命名
