// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"push/internal/model"
)

type (
	IPushLog interface {
		AddPushLog(ctx context.Context, in *model.AddPushLogInput) (err error)
	}
)

var (
	localPushLog IPushLog
)

func PushLog() IPushLog {
	if localPushLog == nil {
		panic("implement not found for interface IPushLog, forgot register?")
	}
	return localPushLog
}

func RegisterPushLog(i IPushLog) {
	localPushLog = i
}
