// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"push/internal/model"
	"push/internal/model/entity"
)

type (
	IPushDevice interface {
		AddPushDevice(ctx context.Context, in *model.AddPushDeviceInput) (err error)
		SetPushDeviceService(ctx context.Context, in *model.SetPushDeviceServiceInput) (out *model.SetPushDeviceServiceOutput, err error)
		GetDeviceInfo(ctx context.Context, in *model.GetPushDeviceInfoInput) (out *entity.PushDevice, err error)
		GetDeviceCount(ctx context.Context, in *model.GetPushDeviceInfoInput) (count int, err error)
		GetDeviceBaseListByServiceId(ctx context.Context, in uint) (out []*entity.PushDevice, err error)
	}
)

var (
	localPushDevice IPushDevice
)

func PushDevice() IPushDevice {
	if localPushDevice == nil {
		panic("implement not found for interface IPushDevice, forgot register?")
	}
	return localPushDevice
}

func RegisterPushDevice(i IPushDevice) {
	localPushDevice = i
}
