// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"push/internal/model"
)

type (
	IPushCore interface {
		PushCore(ctx context.Context, in *model.PushBasicData) (err error)
	}
)

var (
	localPushCore IPushCore
)

func PushCore() IPushCore {
	if localPushCore == nil {
		panic("implement not found for interface IPushCore, forgot register?")
	}
	return localPushCore
}

func RegisterPushCore(i IPushCore) {
	localPushCore = i
}
