// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"push/internal/model"
	"push/internal/model/entity"
)

type (
	IPushService interface {
		SearchPushServiceBySign(ctx context.Context, in *model.PushBasicData) (out *entity.PushService, err error)
		GetPushServiceCount(ctx context.Context, in *model.GetPushDeviceInfoInput) (out int, err error)
		GetPushServiceList(ctx context.Context, input model.GetPushServiceListInput) (output *model.GetPushServiceListOutput, err error)
		AddPushService(ctx context.Context, input model.AddPushServiceInput) (err error)
		SetPushServiceStatus(ctx context.Context, input model.SetPushServiceInput) (err error)
		UpdatePushServicePushTime(ctx context.Context, in uint) (err error)
	}
)

var (
	localPushService IPushService
)

func PushService() IPushService {
	if localPushService == nil {
		panic("implement not found for interface IPushService, forgot register?")
	}
	return localPushService
}

func RegisterPushService(i IPushService) {
	localPushService = i
}
