// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"push/internal/dao/internal"
)

// internalPushLogDao is internal type for wrapping internal DAO implements.
type internalPushLogDao = *internal.PushLogDao

// pushLogDao is the data access object for table push_log.
// You can define custom methods on it to extend its functionality as you wish.
type pushLogDao struct {
	internalPushLogDao
}

var (
	// PushLog is globally public accessible object for table push_log operations.
	PushLog = pushLogDao{
		internal.NewPushLogDao(),
	}
)

// Fill with you ideas below.
