// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ChatUser is the golang structure for table chat_user.
type ChatUser struct {
	Id           uint        `json:"id"             ` // 用户ID
	Username     string      `json:"username"       ` // 用户名
	LastChatTime *gtime.Time `json:"last_chat_time" ` // 上次聊天时间
}
