name: Build and push Docker image

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:${{ steps.get_version.outputs.VERSION }}

      - name: Tag Docker image as latest
        run: docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
            docker push $IMAGE_NAME:${{ steps.get_version.outputs.VERSION }}
            docker push $IMAGE_NAME:latest
      - name: Update k3s deployment
        run: |
          curl -X PUT \
          -H "content-type: application/json" \
          -H "Cookie: KuboardUsername=admin; KuboardAccessKey=6ezinf77jsc8.2ti83pw52p7zi8w5ffibkx88z2pre3a5" \
          -d '{"kind":"deployments","namespace":"hamster","name":"home-net","images":{"hamster1963/nasnetwork_push_go":"hamster1963/nasnetwork_push_go:${{ steps.get_version.outputs.VERSION }}"}}' \
          "http://110.40.156.134:8075/kuboard-api/cluster/huawei/kind/CICDApi/admin/resource/updateImageTag"