# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 代码编译测试

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Get Git Commit Log
      id: git-commit-log
      run: echo "GIT_COMMIT_LOG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

    - name: Get Build Time
      id: build-time
      run: echo "BUILD_TIME=$(date +'%Y.%m.%d.%H:%M:%S')" >> $GITHUB_ENV

    - name: Print Environment Variables
      run: |
        echo "${{env.GIT_COMMIT_LOG}}"
        echo "${{env.BUILD_TIME}}"


    - name: Build
      run: |
        go build -v ./...
        pwd

